-- return {
--   "rose-pine/neovim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     require("rose-pine").setup {
--       styles = {
--         italic = false,
--         transparency = true,
--         bold = false,
--       },
--     }
--
--     vim.cmd "colorscheme rose-pine"
--   end,
-- }
--
-- return {
--   "folke/tokyonight.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     require("tokyonight").setup {}
--     vim.cmd "colorscheme tokyonight-night"
--   end,
-- }
-- return {
--   "catppuccin/nvim",
--   lazy = false,
--   name = "catppuccin",
--   priority = 1000,
--   config = function()
--     require("catppuccin").setup {
--       flavour = "macchiato",
--       no_italic = true,
--     }
--     vim.cmd "colorscheme catppuccin"
--   end,
-- }
--
-- return {
--   "vague-theme/vague.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     require("vague").setup {
--       bold = false,
--       italic = false,
--     }
--     vim.cmd "colorscheme vague"
--   end,
-- }
--
-- return {
--   "ellisonleao/gruvbox.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     require("gruvbox").setup {
--       italic = {
--         strings = false,
--         emphasis = false,
--         comments = false,
--         operators = false,
--         folds = false,
--       },
--     }
--     vim.cmd "colorscheme gruvbox"
--   end,
-- }
--
--
-- return {
--   "sainnhe/gruvbox-material",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.g.gruvbox_material_enable_italic = true
--     vim.cmd.colorscheme "gruvbox-material"
--   end,
-- }
--
-- return {
--   "zenbones-theme/zenbones.nvim",
--   dependencies = "rktjmp/lush.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.opt.background = "l"
--     vim.cmd.colorscheme "zenbones"
--   end,
-- }
--
-- return {
--   "miikanissi/modus-themes.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.cmd.colorscheme "modus"
--   end,
-- }
-- return {
--   "tiagovla/tokyodark.nvim",
--   lazy = false,
--   priority = 1000,
--   opts = {},
--   config = function(_, opts)
--     require("tokyodark").setup(opts)
--     vim.cmd [[colorscheme tokyodark]]
--   end,
-- }

return {
  "bluz71/vim-moonfly-colors",
  lazy = false,
  priority = 1000,
  name = "moonfly",
  config = function()
    vim.cmd.colorscheme "moonfly"
  end,
}
